services:
  - type: web
    name: wavechat
    runtime: node
    plan: starter
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma db push --skip-generate && node server.cjs start
    disk:
      name: wavechat-data
      mountPath: /var/data
      sizeGB: 5
    envVars:
      - key: DATABASE_URL
        value: file:/var/data/dev.db
      - key: STORAGE_DIR
        value: /var/data
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
